### ISSUE TITLE
Unable to obtain authentication token

### ISSUE THREAD

**Issue by moldybeats** [bartosz-maciaszek/php-rtm#1]
When trying to obtain an API authentication token using $rtm->getService(Rtm::SERVICE_AUTH)->getToken(), I get the following error:
"Auth token not set".

It looks like the createRequest() method in Client.php assumes an auth_token parameter always exists. However, when using the rtm.auth.getToken API method, we won't be able to provide this parameter.

Is there a way to work around this?

**Comment by bartosz-maciaszek** [comment]
You're right, these is a problem with it. Auth token should be set from session, but if there is a fresh session without proper parameter, exception is thrown.
As a simple workaround I can recommend setting auth token to some invalid value in `Rtm` class instead of using null.

```
$rtm->setAuthToken('test');
```

In sample app (in `index.php` and `rtm.php`) there should be:

```
$rtm = new Rtm;
$rtm->setApiKey(API_KEY);
$rtm->setSecret(SECRET);
$rtm->setAuthToken(isset($_SESSION['RTM_AUTH_TOKEN']) ? $_SESSION['RTM_AUTH_TOKEN'] : 'test');
```

I'll try to fix it in upcoming version.

Thanks,
Bartosz

**Comment by bartosz-maciaszek** [comment]
Try version 1.0.3.

**Comment by moldybeats** [comment]
Authentication is working great for me now. Thanks!
